# Generated by Django 4.2 on 2024-05-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleHockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('time', models.TimeField(verbose_name='Время проведения матча')),
                ('first_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules1', to='common.hockeyteam', verbose_name='Комманда 1')),
                ('second_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules2', to='common.hockeyteam', verbose_name='Комманда 2')),
            ],
            options={
                'verbose_name': 'Хоккейный матч',
                'verbose_name_plural': 'Хоккейные матчи',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleFootball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('time', models.TimeField(verbose_name='Время проведения матча')),
                ('first_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules1', to='common.footballteam', verbose_name='Комманда 1')),
                ('second_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules2', to='common.footballteam', verbose_name='Комманда 2')),
            ],
            options={
                'verbose_name': 'Футбольный матч',
                'verbose_name_plural': 'Футбольные матчи',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBassketball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения матча')),
                ('time', models.TimeField(verbose_name='Время проведения матча')),
                ('first_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules1', to='common.basketballteam', verbose_name='Комманда 1')),
                ('second_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules2', to='common.basketballteam', verbose_name='Комманда 2')),
            ],
            options={
                'verbose_name': 'Баскетбольный матч',
                'verbose_name_plural': 'Баскетбольные матчи',
                'ordering': ['date', 'time'],
            },
        ),
    ]
