# Generated by Django 5.0.4 on 2024-04-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autonews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportexpressarticle',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='sportexpressarticle',
            name='likes',
        ),
    ]
