# Generated by Django 4.2 on 2024-05-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_tour', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Тур по баскетболу',
                'verbose_name_plural': 'Туры по баскетболу',
            },
        ),
        migrations.CreateModel(
            name='FootballTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_tour', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Тур по футболлу',
                'verbose_name_plural': 'Туры по футболлу',
            },
        ),
        migrations.CreateModel(
            name='HockeyTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_tour', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Тур по хоккею',
                'verbose_name_plural': 'Туры по хоккею',
            },
        ),
        migrations.CreateModel(
            name='HockeyTourMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='счет')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedulehockey', verbose_name='Матч')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tours.hockeytour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Матч тура по хоккею',
                'verbose_name_plural': 'Матчи тура по хоккею',
            },
        ),
        migrations.CreateModel(
            name='FootballTourMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='счет')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedulefootball', verbose_name='Матч')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tours.footballtour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Матч тура по футболу',
                'verbose_name_plural': 'Матчи тура по футболу',
            },
        ),
        migrations.CreateModel(
            name='BasketballTourMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='счет')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedulebassketball', verbose_name='Матч')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tours.basketballtour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Матч тура по баскетболу',
                'verbose_name_plural': 'Матчи тура по баскетболу',
            },
        ),
    ]
