# Generated by Django 4.2 on 2024-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название комманды')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Лого комманды')),
            ],
            options={
                'verbose_name': 'Баскетбольная команда',
                'verbose_name_plural': 'Баскетбольные команды',
                'db_table': 'teams_basketballteam',
            },
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название комманды')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Лого комманды')),
            ],
            options={
                'verbose_name': 'Футбольная каманда',
                'verbose_name_plural': 'Футбольные каманды',
                'db_table': 'teams_footballteam',
            },
        ),
        migrations.CreateModel(
            name='HockeyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название комманды')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Лого комманды')),
            ],
            options={
                'verbose_name': 'Хоккейная клмманда',
                'verbose_name_plural': 'Хоккейные клмманды',
                'db_table': 'teams_hockeyteam',
            },
        ),
    ]
