# Generated by Django 4.2 on 2024-05-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basketballteam',
            table=None,
        ),
        migrations.AlterModelTable(
            name='footballteam',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hockeyteam',
            table=None,
        ),
    ]
