# Generated by Django 4.2 on 2024-05-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Спорт', 'verbose_name_plural': 'Виды спорта'},
        ),
    ]
